apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
  labels:
    name: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      name: audit
  template:
    metadata:
      labels:
        name: audit
    spec:
      containers:
      - name: audit
        image: 1631995/audit
        ports:
        - containerPort: 8000
      hostname: audit