version: "3.3"
services:
  web1:
    build: ./currency_swap
    hostname: swap
    network_mode: host
    ports:
       - "8000:8000"
  web2:

    build: ./Audit
    hostname: audit
    ports:
       - "5000:8000"

  redis: 
    image: "redis:alpine" 

